name: "draft"

env: 
  # VITE_GRAPHQL_ENDPOINT_CLOUD: "https://api.sonic-sync.com/graphql"
  PUBLIC_API_HOST: "https://api.sonic-sync.com"
on:
  workflow_dispatch: 
  # push:
  #   branches:
  #     - main 

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.14.1
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        # You can remove libayatana-appindicator3-dev if you don't use the system tray feature.
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - name: install arm64 rust target (macos only)
        if: matrix.platform == 'macos-latest'
        run: rustup target add aarch64-apple-darwin
        

      - name: install app dependencies and build it
        # env:   
        run: pnpm i && pnpm build


      - uses: tauri-apps/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          labels: ${{ matrix.platform }}
          args: ${{ matrix.platform == 'macos-latest' && '--target universal-apple-darwin' || '' }}
          tagName: draft-sonic-sync-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "draft-Sonic Sync v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: true
