name: "publish"

env: 
  VITE_GRAPHQL_ENDPOINT_CLOUD: "http://ec2-18-204-44-125-.compute-1.amazon.com:4000/graphql"
on:
  workflow_dispatch: 
  push:
    branches:
      - master

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.14.1
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install arm64 rust target (macos only)
        if: matrix.platform == 'macos-latest'
        run: rustup target add aarch64-apple-darwin
        

      - name: install app dependencies and build it
        env:   
        run: pnpm i && pnpm build


      - uses: tauri-apps/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ matrix.platform == 'macos-latest' && '--target universal-apple-darwin' || '' }}
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: true
